---
title: "Untitled"
format: html
editor: visual
---

```{r}
theme_set(theme_classic(base_size = 16, base_family = "Roboto Slab"))


"#f6f7f1"
"#f1f6f4"
"#f3f4f5"
"#DBE0E1"
"#FBF5F0"


theme_update(
  panel.background = element_rect(fill = "#f1f6f4"),
  plot.background = element_rect(fill = "#f1f6f4"),
  plot.margin = margin(.8, 1, .7, .8, "cm"),
  plot.title = element_text(
    size = 20,
    face = "bold",
    margin = margin(b = .25, unit = "cm")
  ),
  plot.title.position = "plot",
  plot.caption.position = "plot",
  plot.subtitle = element_text(face = "italic"),
  axis.title.x = element_text(margin = margin(t = .5, unit = "cm")),
  plot.caption = element_text(face = "italic", size = 12 
                              ) 
  )

point_data <- overall_index %>% filter(date == min(date)|date ==max(date)) %>% 
  mutate(across(is.numeric, round, digits =2))

# Plot overall index with overall price change
overall_growth <- ggplot(overall_index, aes(x = date, y = overall_index)) +
  geom_line(color = "#7d3a46", linewidth = 1.5) +
  geom_point(data = point_data,
    fill = "#7d3a46",
             size = 4, 
             color = "#7d3a46", 
             stroke = 1 # The width of the border, i.e. stroke. 
               )+
  geom_text(data = point_data,
            aes(label = overall_index), color = "black",
            size = 4, nudge_x = 0.1, vjust = -1.0, 
            fontface = "bold"
               )+
  annotate("rect", 
           xmin = as.Date("2023-07-01"), xmax = as.Date("2024-07-01"),
           ymin = -Inf, ymax = Inf,
           alpha = 0.1, fill = "red") + 
  
  annotate(geom = "text", 
           x = as.Date("2024-07-01"), y = 90,
           label = "Кетма-кет 12 ой пасайишдан сўнг\n нархлар кўтарилишни бошлаган",
           color = "darkblue", 
           fontface = "bold",
           size = 4) +
  annotate("curve",
            x = as.Date("2024-07-10"), y = 88.5,
            xend = as.Date("2024-07-01"), yend =81.18661,
            curvature = -0.4, color="black",
            arrow = arrow(
              type = "closed",
              length = unit(10, "pt")))+
labs(title = "Маҳаллий автомобиллар нарх индекси",
        caption = "Манба: Иқтисодий тадқиқотлар ва ислоҳотлар марказиn\ томонидан очиқ сайтларда берилган эълонлар асосида ҳисобланган.",
       x = NULL,
       y = NULL ) +
  scale_x_date(
    date_breaks = "1 months",
    # date_labels = "%b '%y", 
    labels = scales::label_date_short(),
    limits = as.Date(c("2023-01-01", "2024-09-05")),
    expand = expansion(mult=0.03)
    ) +
  scale_y_continuous(
    breaks = seq(0, 110, by=10),
    limits = c(70, 110),
    expand = expansion(mult=0.01)
                     )

# # Save the overall chart
# ggsave(
#   filename = "overall_growth.svg",
#   plot = overall_growth,
#   width  =  10,
#   height =  7,
#   units  = "in",
#   dpi    = 320
# )
```

### **PLOT 2**

```{r}

"#edf3f6"

theme_update(
  panel.background = element_rect(fill = "#f1f6f4", color = "#f1f6f4"), 
  plot.background = element_rect(fill = "#f1f6f4", color = "#f1f6f4"),
  plot.margin = margin(.8, 1, .7, .8, "cm"),
  plot.title = element_text(
    size = 20,
    face = "bold",
    margin = margin(b = .25, unit = "cm")
  ),
  plot.title.position = "plot",
  plot.subtitle = element_text(
    face = "italic"
  ),
  axis.title.x = element_text(
    margin = margin(t = .5, unit = "cm")
  ),
  plot.caption = element_text(
    face = "italic",
    size = 14, 
    margin = margin(t = 0.5, unit = "cm")
  )
  )

# Improved growth rate chart with better label visibility
monthly_growth <- ggplot(overall_index, 
                         aes(x = date, y = growth_rate, fill = growth_rate >= 0,
                             )
                         ) +
  geom_col() +
  geom_bar_text(aes(label = round(growth_rate, 1)
                    ),
                contrast = TRUE
                )+
  scale_fill_manual(values = c("TRUE" = "skyblue", "FALSE" = "lightcoral")) +
  theme(legend.position = "none") +
  labs(title = "Автомобиллар нархининг ўзгариши",
       subtitle = "Ойлик ўсиш суръати, %да",
       x = NULL,
       y = NULL) +
  scale_x_date(
    date_breaks = "1 months",
    # date_labels = "%b '%y", 
    labels = scales::label_date_short(),
    #limits = as.Date(c("2023-01-01", "2024-09-01")),
    expand = expansion(mult=0.01)
    ) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  coord_cartesian(ylim = c(min(overall_index$growth_rate) - 1, max(overall_index$growth_rate) + 1))

# ggsave(
#   filename = "plot3.svg",
#   plot = monthly_growth, 
#   width = 10.7, 
#   height = 7.38,
#   units = "in"
# )
```

### **SAVING PLTOS**

```{r}
overall_chart <- overall_growth + monthly_growth 

# Save the overall chart
ggsave(
  filename = "chevrolet_overall_charts.svg",
  plot = overall_chart,
  width  =  20,
  height =  7.1,
  units  = "in",
  dpi    = 320,
)
```
